### PR TITLE
Improve styles and notification text

### PR DESCRIPTION
**Pull request by Sunegi**
- Styles updated to match forum
- Layout, spacing, and padding
- Notification text improved
- Converted tabs to spaces

### CODE REVIEW

**Comment by kavhayushar** [comment]
Very nice 👍

**Comment by mayim-chayim** [comment]
nice button styling 

looks like we all use different styles of indentation and spacing

**Comment by YisroelTech** [comment]
Nice!

**Comment by Sunegi** [comment]
Thanks all, appreciate your feedback.

**Review by kavhayushar — APPROVED** [review]

**Pull request merged**
