### PR TITLE
get live notifications on new response client side only

### PR DESCRIPTION
**Pull request by mayim-chayim**

### CODE REVIEW

**Comment by mayim-chayim** [comment]
the PR is not yet ready there is some issues that needs to be resolved 

- [ ] the request does send the cookies, causing the new posts to be marked as read 
- [ ] and we need to check for a new page

**Comment by kavhayushar** [comment]
@mayim-chayim nice work.
You still need to change the first url to avoid marking as read.

Also we can use fetch() instead of ajax so we can specify to omit sending along the cookies.
`fetch("https://www.ivelt.com",{credentials: 'omit'})`

Thank you very much.

**Comment by mayim-chayim** [comment]
it's marking it as unread with the `mark_unread_url`

I think it's ready

is 20 seconds the ring interval?

**Comment by mordechairoth** [comment]
@mayim-chayim Thanks for your submission, it looks great.
Please change the casing to camel case, also please change the var declarations to let, as I want the code in the project to be consistent.

**Comment by mordechairoth** [comment]
@mayim-chayim  while testing I noticed that when a new message comes in the message box pops up, there is no way for the user to NOT reload the page or remove the pop up from the page, can you add a cancel (איגנאריר) button to the pop up?

**Comment by mayim-chayim** [comment]
> @mayim-chayim while testing I noticed that when a new message comes in the message box pops up, there is no way for the user to NOT reload the page or remove the pop up from the page, can you add a cancel (איגנאריר) button to the pop up?

changed to a button below the last post, you can just ignore it

**Pull request merged**
